import { jsPDF } from 'jspdf';
import JSZip from 'jszip';
import {
  calculateKdpCoverDimensions,
  calculateKdpInsideMargin,
  calculateKdpSpineWidth,
  findTrimSize,
} from '../constants/kdp';
import {
  KDPExportPackageFile,
  KDPExportPackageResult,
  KDPPreflightReport,
  KDPProjectConfig,
} from '../types/kdp';
import { DocumentModel, Project } from '../types/project';
import { KDPPreflightService } from './kdpPreflightService';
import { PdfExportService } from './pdfExportService';

export class KDPExportService {
  /**
   * Builds the structured metadata.json file content
   */
  public static generateMetadataJson(project: Project): Record<string, any> {
    const config: KDPProjectConfig = project.kdpConfig || {
      bookId: project.id,
      title: project.name,
      subtitle: project.metadata?.subtitle || '',
      authorName: project.metadata?.author || 'KDP Creator',
      contributorName: '',
      language: project.metadata?.language || 'English',
      description: project.metadata?.description || project.description || '',
      keywords: project.metadata?.keywords || [],
      categories: project.metadata?.category ? [project.metadata.category] : [],
      bookType: 'Puzzle Book',
      format: 'Paperback',
      trimSize: project.kdpSettings?.trimSize?.name || '8.5" × 11"',
      pageCount: project.pageCount || 80,
      interiorType: 'Black & White',
      paperType: 'White',
      bleed: 'No Bleed',
      coverFinish: 'Matte',
      isbnType: 'Free KDP ISBN',
      aiContentType: 'AI-generated',
      marketplace: 'amazon.com',
      publicationStatus: 'DRAFT',
      validationStatus: 'NOT_VALIDATED',
      validationErrors: [],
      validationWarnings: [],
      createdAt: project.createdAt,
      updatedAt: project.updatedAt,
    };

    return {
      title: config.title || project.name,
      subtitle: config.subtitle || '',
      author: config.authorName || 'KDP Creator',
      contributor: config.contributorName || '',
      language: config.language || 'English',
      description: config.description || project.description || '',
      keywords: config.keywords || [],
      categories: config.categories || [],
      bookType: config.bookType || 'Puzzle Book',
      format: config.format || 'Paperback',
      trimSize: config.trimSize || '8.5" × 11"',
      pageCount: config.pageCount || project.pageCount || 80,
      interiorType: config.interiorType || 'Black & White',
      paperType: config.paperType || 'White',
      bleed: config.bleed || 'No Bleed',
      coverFinish: config.coverFinish || 'Matte',
      isbnType: config.isbnType || 'Free KDP ISBN',
      isbn: config.isbn || '',
      aiContentType: config.aiContentType || 'AI-generated',
      marketplace: config.marketplace || 'amazon.com',
      exportTimestamp: new Date().toISOString(),
      studioVersion: 'KDP Book & Puzzle Studio v2.5',
    };
  }

  /**
   * Builds clean plain text description
   */
  public static generateDescriptionText(project: Project): string {
    const title = project.kdpConfig?.title || project.name;
    const subtitle = project.kdpConfig?.subtitle || project.metadata?.subtitle || '';
    const desc = project.kdpConfig?.description || project.metadata?.description || project.description || '';

    return `=====================================================
AMAZON KDP BOOK DESCRIPTION: ${title.toUpperCase()}
${subtitle ? `SUBTITLE: ${subtitle}\n` : ''}=====================================================

${desc}

-----------------------------------------------------
BOOK SPECIFICATIONS:
- Book Type: ${project.kdpConfig?.bookType || 'Puzzle Book'}
- Format: ${project.kdpConfig?.format || 'Paperback'}
- Trim Size: ${project.kdpConfig?.trimSize || '8.5" × 11"'}
- Page Count: ${project.kdpConfig?.pageCount || project.pageCount || 80} Pages
- Interior: ${project.kdpConfig?.interiorType || 'Black & White'} on ${project.kdpConfig?.paperType || 'White'} Paper
- Cover Finish: ${project.kdpConfig?.coverFinish || 'Matte'}
- Solutions: Full answer keys included in back matter
-----------------------------------------------------
Generated by KDP Book & Puzzle Studio
`;
  }

  /**
   * Builds clean 7-keywords plain text
   */
  public static generateKeywordsText(project: Project): string {
    const keywords = (project.kdpConfig?.keywords || project.metadata?.keywords || []).filter(k => Boolean(k && k.trim()));

    let output = `=====================================================
AMAZON KDP BACKEND SEARCH KEYWORDS (Up to 7 slots)
=====================================================\n\n`;

    if (keywords.length === 0) {
      output += `(No keywords specified yet. Add up to 7 search phrases in KDP Metadata tab.)\n`;
    } else {
      keywords.forEach((kw, i) => {
        output += `Slot #${i + 1}: ${kw}\n`;
      });
      output += `\nComma-separated string for bulk pasting:\n`;
      output += keywords.join(', ') + '\n';
    }

    output += `\n-----------------------------------------------------
Tip: Avoid repeating words already in your title or subtitle.
Target phrases that readers actively search on Amazon.
`;
    return output;
  }

  /**
   * Generates the official KDP-Validation-Report.pdf
   */
  public static generateValidationReportPdf(
    project: Project,
    report: KDPPreflightReport
  ): Blob {
    // 8.5 x 11 inch portrait PDF
    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'in',
      format: [8.5, 11],
    });

    const config = project.kdpConfig || {
      title: project.name,
      authorName: project.metadata?.author || 'Creator',
      bookType: 'Puzzle Book',
      format: 'Paperback',
      trimSize: '8.5" × 11"',
      pageCount: project.pageCount || 80,
      interiorType: 'Black & White',
      paperType: 'White',
      bleed: 'No Bleed',
      coverFinish: 'Matte',
      aiContentType: 'AI-generated',
    };

    // Header Background
    doc.setFillColor(17, 24, 39); // Dark #111827
    doc.rect(0, 0, 8.5, 1.4, 'F');

    // Header Title
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text('AMAZON KDP PREFLIGHT & PUBLISHING VALIDATION REPORT', 0.6, 0.55);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(209, 213, 219);
    doc.text(`Generated on: ${new Date(report.timestamp).toLocaleString()} | KDP Studio Compliance Engine`, 0.6, 0.82);

    // Status Banner
    let bannerColor = [16, 185, 129]; // Emerald (Pass)
    let statusTitle = 'KDP READY — ALL MANDATORY CHECKS PASSED';
    if (report.status === 'FAIL') {
      bannerColor = [239, 68, 68]; // Red
      statusTitle = 'VALIDATION FAILED — FIX BLOCKING ERRORS BEFORE EXPORT';
    } else if (report.status === 'WARNING') {
      bannerColor = [245, 158, 11]; // Amber
      statusTitle = 'READY WITH WARNINGS — REVIEW RECOMMENDED BEFORE PUBLISHING';
    }

    doc.setFillColor(bannerColor[0], bannerColor[1], bannerColor[2]);
    doc.rect(0.6, 1.6, 7.3, 0.45, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(statusTitle, 0.8, 1.88);

    // Summary Metrics Cards
    doc.setDrawColor(229, 231, 235);
    doc.setFillColor(249, 250, 251);

    // Card 1: Errors
    doc.roundedRect(0.6, 2.2, 2.25, 0.7, 0.05, 0.05, 'FD');
    doc.setTextColor(107, 114, 128);
    doc.setFontSize(8);
    doc.text('BLOCKING ERRORS', 0.75, 2.42);
    doc.setTextColor(report.errors.length > 0 ? 220 : 55, report.errors.length > 0 ? 38 : 65, report.errors.length > 0 ? 38 : 81);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(String(report.errors.length), 0.75, 2.75);

    // Card 2: Warnings
    doc.roundedRect(3.1, 2.2, 2.25, 0.7, 0.05, 0.05, 'FD');
    doc.setTextColor(107, 114, 128);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text('WARNINGS', 3.25, 2.42);
    doc.setTextColor(report.warnings.length > 0 ? 217 : 55, report.warnings.length > 0 ? 119 : 65, report.warnings.length > 0 ? 6 : 81);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(String(report.warnings.length), 3.25, 2.75);

    // Card 3: Passed Checks
    doc.roundedRect(5.65, 2.2, 2.25, 0.7, 0.05, 0.05, 'FD');
    doc.setTextColor(107, 114, 128);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text('PASSED CHECKS', 5.8, 2.42);
    doc.setTextColor(16, 185, 129);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.text(String(report.summary.passed), 5.8, 2.75);

    // Project Specifications Table
    doc.setDrawColor(229, 231, 235);
    doc.setFillColor(243, 244, 246);
    doc.rect(0.6, 3.1, 7.3, 0.3, 'F');
    doc.setTextColor(17, 24, 39);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('MANUSCRIPT SPECIFICATIONS', 0.75, 3.3);

    const specs = [
      ['Book Title:', (config.title || project.name).slice(0, 50)],
      ['Author / Imprint:', config.authorName || 'KDP Creator'],
      ['Book Type:', config.bookType || 'Puzzle Book'],
      ['Format & Trim:', `${config.format || 'Paperback'} • ${config.trimSize || '8.5" × 11"'}`],
      ['Page Count:', `${project.pageCount || config.pageCount || 80} Interior Pages`],
      ['Interior & Paper:', `${config.interiorType || 'Black & White'} on ${config.paperType || 'White'} Paper`],
      ['Bleed & Finish:', `${config.bleed || 'No Bleed'} • ${config.coverFinish || 'Matte'} Cover`],
      ['AI Disclosure:', config.aiContentType || 'AI-generated Content (Declared)'],
    ];

    let currentY = 3.6;
    doc.setFontSize(8.5);

    specs.forEach(([label, val], idx) => {
      const col = idx % 2 === 0 ? 0.75 : 4.4;
      const rowY = currentY + Math.floor(idx / 2) * 0.28;

      doc.setFont('helvetica', 'bold');
      doc.setTextColor(75, 85, 99);
      doc.text(label, col, rowY);

      doc.setFont('helvetica', 'normal');
      doc.setTextColor(17, 24, 39);
      doc.text(val, col + 1.4, rowY);
    });

    // Check Categories & Detail Items
    currentY = 5.0;
    doc.setFillColor(243, 244, 246);
    doc.rect(0.6, currentY, 7.3, 0.3, 'F');
    doc.setTextColor(17, 24, 39);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('PREFLIGHT CHECK RESULTS BY DOMAIN', 0.75, currentY + 0.2);

    currentY += 0.45;

    report.checks.forEach(check => {
      if (currentY > 10.0) {
        doc.addPage([8.5, 11], 'portrait');
        currentY = 0.8;
      }

      // Check Status Symbol / Icon
      let symbol = '✓';
      let iconColor = [16, 185, 129];
      if (check.status === 'FAIL') {
        symbol = '✕';
        iconColor = [239, 68, 68];
      } else if (check.status === 'WARNING') {
        symbol = '!';
        iconColor = [245, 158, 11];
      }

      doc.setFillColor(iconColor[0], iconColor[1], iconColor[2]);
      doc.circle(0.8, currentY - 0.04, 0.1, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7);
      doc.text(symbol, 0.77, currentY - 0.01);

      // Category & Name
      doc.setTextColor(17, 24, 39);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(8.5);
      doc.text(`[${check.category}] ${check.name}`, 1.0, currentY);

      // Message
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(75, 85, 99);
      doc.setFontSize(8);
      const splitMsg = doc.splitTextToSize(check.message, 6.7);
      doc.text(splitMsg, 1.0, currentY + 0.16);

      currentY += 0.2 + splitMsg.length * 0.14;
    });

    // Footer note
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(7.5);
    doc.setTextColor(156, 163, 175);
    doc.text(
      'Note: This preflight report verifies mechanical and metadata compatibility for Amazon KDP Print. Direct Amazon account publishing will be added when officially supported.',
      0.6,
      10.5
    );

    return doc.output('blob');
  }

  /**
   * Generates a basic calculated full wrap cover PDF
   */
  public static generateCoverPdf(project: Project): Blob {
    const trimObj = project.kdpSettings?.trimSize || findTrimSize(project.kdpConfig?.trimSize || '8.5x11');
    const pageCount = project.kdpConfig?.pageCount || project.pageCount || 80;
    const paperType = (project.kdpConfig?.paperType as any) || 'White';
    const spineWidth = calculateKdpSpineWidth(pageCount, paperType);
    const coverDims = calculateKdpCoverDimensions(trimObj.width, trimObj.height, spineWidth);

    const doc = new jsPDF({
      orientation: 'landscape',
      unit: 'in',
      format: [coverDims.width, coverDims.height],
    });

    const bgCoverColor = project.metadata?.coverColor || '#111827';
    const colorMode = PdfExportService.parseColor(bgCoverColor, 'rgb');

    // Background fill
    doc.setFillColor(colorMode.r, colorMode.g, colorMode.b);
    doc.rect(0, 0, coverDims.width, coverDims.height, 'F');

    const bleed = 0.125;
    const backCoverX = bleed;
    const backCoverWidth = trimObj.width;
    const spineX = bleed + trimObj.width;
    const frontCoverX = spineX + spineWidth;
    const frontCoverWidth = trimObj.width;

    // Spine guide lines (subtle dashed)
    doc.setDrawColor(200, 200, 200);
    doc.setLineDashPattern([0.05, 0.05], 0);
    doc.line(spineX, 0, spineX, coverDims.height);
    doc.line(spineX + spineWidth, 0, spineX + spineWidth, coverDims.height);

    // Front Cover Content
    const frontCenterX = frontCoverX + frontCoverWidth / 2;
    const title = project.kdpConfig?.title || project.name;
    const subtitle = project.kdpConfig?.subtitle || project.metadata?.subtitle || '';
    const author = project.kdpConfig?.authorName || project.metadata?.author || 'KDP Creator';

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    const splitTitle = doc.splitTextToSize(title.toUpperCase(), frontCoverWidth - 1.2);
    doc.text(splitTitle, frontCenterX, coverDims.height * 0.35, { align: 'center' });

    if (subtitle) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(12);
      doc.setTextColor(229, 231, 235);
      const splitSub = doc.splitTextToSize(subtitle, frontCoverWidth - 1.4);
      doc.text(splitSub, frontCenterX, coverDims.height * 0.5, { align: 'center' });
    }

    // Author
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(255, 255, 255);
    doc.text(author, frontCenterX, coverDims.height * 0.85, { align: 'center' });

    // Spine text (Only if page count >= 79 per Amazon KDP rules)
    if (pageCount >= 79 && spineWidth >= 0.175) {
      doc.saveGraphicsState();
      // Rotate for spine
      doc.setFontSize(9);
      doc.setTextColor(243, 244, 246);
      doc.text(title, spineX + spineWidth / 2, coverDims.height / 2, {
        align: 'center',
        angle: 270,
      });
      doc.restoreGraphicsState();
    }

    // Back cover blurb
    const backCenterX = backCoverX + backCoverWidth / 2;
    const desc = project.kdpConfig?.description || project.description || '';
    if (desc) {
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.setTextColor(229, 231, 235);
      const splitDesc = doc.splitTextToSize(desc, backCoverWidth - 1.4);
      doc.text(splitDesc, backCenterX, coverDims.height * 0.3, { align: 'center' });
    }

    // Barcode area outline placeholder (Standard KDP bottom right of back cover)
    doc.setDrawColor(150, 150, 150);
    doc.setFillColor(255, 255, 255);
    doc.rect(backCoverX + backCoverWidth - 2.2, coverDims.height - 1.5, 2.0, 1.2, 'FD');
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(7.5);
    doc.text('Amazon KDP Barcode Location', backCoverX + backCoverWidth - 1.2, coverDims.height - 0.85, {
      align: 'center',
    });

    return doc.output('blob');
  }

  /**
   * Builds the complete KDP-Ready Export Package
   */
  public static async buildExportPackage(
    project: Project,
    document?: DocumentModel | null,
    onProgress?: (step: string, percentage: number) => void
  ): Promise<KDPExportPackageResult> {
    onProgress?.('Validating KDP Compliance...', 15);

    // 1. Run full preflight
    const preflight = KDPPreflightService.validate(project, document);

    // 2. Prepare text and metadata files
    onProgress?.('Generating Structured Metadata...', 35);
    const metadataJson = this.generateMetadataJson(project);
    const metadataJsonStr = JSON.stringify(metadataJson, null, 2);
    const metadataJsonBlob = new Blob([metadataJsonStr], { type: 'application/json' });

    const descriptionText = this.generateDescriptionText(project);
    const descriptionBlob = new Blob([descriptionText], { type: 'text/plain;charset=utf-8' });

    const keywordsText = this.generateKeywordsText(project);
    const keywordsBlob = new Blob([keywordsText], { type: 'text/plain;charset=utf-8' });

    onProgress?.('Compiling Validation Report PDF...', 55);
    const validationReportBlob = this.generateValidationReportPdf(project, reportToPreflight(preflight));

    // 3. Render interior PDF
    onProgress?.('Rendering Print-Ready Vector Interior PDF...', 75);
    let interiorPdfBlob: Blob | undefined;
    try {
      if (document && document.pages && document.pages.length > 0) {
        const interiorResult = await PdfExportService.exportInteriorPdf(
          project,
          document,
          {
            format: 'interior_pdf',
            colorMode: project.kdpConfig?.interiorType === 'Black & White' ? 'grayscale' : 'rgb',
            includeBleed: project.kdpConfig?.bleed === 'Bleed',
            includeCropMarks: false,
            pageRange: 'all',
            paperStock: (project.kdpConfig?.paperType as any) || 'White',
          }
        );
        interiorPdfBlob = interiorResult.blob;
      }
    } catch (err) {
      console.warn('Interior PDF rendering error:', err);
    }

    // 4. Generate cover PDF
    onProgress?.('Computing Full Wrap Cover PDF...', 85);
    const coverPdfBlob = this.generateCoverPdf(project);

    // 5. Assemble package inventory
    const files: KDPExportPackageFile[] = [
      {
        name: 'metadata.json',
        type: 'application/json',
        size: metadataJsonBlob.size,
        blob: metadataJsonBlob,
        content: metadataJsonStr,
        isMandatory: true,
        status: 'READY',
        description: 'Structured machine-readable KDP publishing manifest.',
      },
      {
        name: 'description.txt',
        type: 'text/plain',
        size: descriptionBlob.size,
        blob: descriptionBlob,
        content: descriptionText,
        isMandatory: true,
        status: 'READY',
        description: 'Formatted product blurb and book specifications for KDP listing.',
      },
      {
        name: 'keywords.txt',
        type: 'text/plain',
        size: keywordsBlob.size,
        blob: keywordsBlob,
        content: keywordsText,
        isMandatory: true,
        status: 'READY',
        description: '7-keyword backend search phrases formatted for quick pasting.',
      },
      {
        name: 'KDP-Validation-Report.pdf',
        type: 'application/pdf',
        size: validationReportBlob.size,
        blob: validationReportBlob,
        isMandatory: true,
        status: 'READY',
        description: 'Comprehensive KDP preflight verification certificate.',
      },
      {
        name: 'interior.pdf',
        type: 'application/pdf',
        size: interiorPdfBlob?.size || 0,
        blob: interiorPdfBlob,
        isMandatory: true,
        status: interiorPdfBlob ? 'READY' : 'ERROR',
        description: 'Complete high-resolution vector print interior manuscript.',
      },
      {
        name: 'cover.pdf',
        type: 'application/pdf',
        size: coverPdfBlob.size,
        blob: coverPdfBlob,
        isMandatory: false,
        status: 'READY',
        description: 'Full wrap cover calculation with spine and bleed boundaries.',
      },
    ];

    // Check blocking errors
    const canExport = preflight.status !== 'FAIL';
    const blockingReasons = preflight.errors;

    // 6. Build ZIP bundle
    onProgress?.('Packing KDP Ready ZIP Bundle...', 95);
    const zip = new JSZip();
    const folder = zip.folder('kdp-export') || zip;

    folder.file('metadata.json', metadataJsonStr);
    folder.file('description.txt', descriptionText);
    folder.file('keywords.txt', keywordsText);
    folder.file('KDP-Validation-Report.pdf', validationReportBlob);
    folder.file('cover.pdf', coverPdfBlob);

    if (interiorPdfBlob) {
      folder.file('interior.pdf', interiorPdfBlob);
    }

    const zipBlob = await zip.generateAsync({ type: 'blob' });
    onProgress?.('Complete!', 100);

    return {
      success: true,
      canExport,
      blockingReasons: blockingReasons.length > 0 ? blockingReasons : undefined,
      files,
      zipBlob,
      metadataJson,
      descriptionText,
      keywordsText,
      validationReport: preflight,
      timestamp: new Date().toISOString(),
    };
  }

  /**
   * Triggers a browser download for a Blob
   */
  public static triggerDownload(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

function reportToPreflight(rep: KDPPreflightReport): KDPPreflightReport {
  return rep;
}
