import { Asset } from '../types';

export const DEFAULT_ASSETS: Asset[] = [
  // Shapes
  {
    id: 'shape-rect',
    name: 'Rounded Rectangle',
    category: 'Shapes',
    type: 'shape',
    url: 'rounded-rect',
    tags: ['box', 'frame', 'container'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'shape-circle',
    name: 'Geometric Circle',
    category: 'Shapes',
    type: 'shape',
    url: 'circle',
    tags: ['circle', 'dot', 'badge'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'shape-star',
    name: '5-Point Star',
    category: 'Shapes',
    type: 'shape',
    url: 'star',
    tags: ['star', 'rating', 'decorative'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'shape-heart',
    name: 'Heart Shape',
    category: 'Shapes',
    type: 'shape',
    url: 'heart',
    tags: ['heart', 'love', 'coloring'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  // Icons
  {
    id: 'icon-sparkles',
    name: 'Magic Sparkles',
    category: 'Icons',
    type: 'svg',
    url: 'sparkles',
    tags: ['sparkles', 'magic', 'accent'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'icon-flower',
    name: 'Botanical Bloom',
    category: 'Icons',
    type: 'svg',
    url: 'flower',
    tags: ['flower', 'nature', 'coloring', 'journal'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'icon-sun',
    name: 'Sun Symbol',
    category: 'Icons',
    type: 'svg',
    url: 'sun',
    tags: ['sun', 'weather', 'morning', 'planner'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'icon-book',
    name: 'Open Book',
    category: 'Icons',
    type: 'svg',
    url: 'book-open',
    tags: ['book', 'reading', 'education'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'icon-feather',
    name: 'Quill Feather',
    category: 'Icons',
    type: 'svg',
    url: 'feather',
    tags: ['feather', 'writing', 'vintage'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'icon-check-square',
    name: 'Habit Checkbox',
    category: 'Icons',
    type: 'svg',
    url: 'check-square',
    tags: ['checkbox', 'planner', 'todo'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  // Borders & Headers
  {
    id: 'border-vintage',
    name: 'Vintage Double Frame',
    category: 'Borders',
    type: 'pattern',
    url: 'vintage-double',
    tags: ['border', 'frame', 'vintage', 'classic'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'border-corner-flourish',
    name: 'Corner Flourish',
    category: 'Borders',
    type: 'pattern',
    url: 'corner-flourish',
    tags: ['corner', 'ornament', 'flourish'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'border-scalloped',
    name: 'Scalloped Edge',
    category: 'Borders',
    type: 'pattern',
    url: 'scalloped',
    tags: ['scallop', 'kids', 'cute'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  // Backgrounds & Textures
  {
    id: 'bg-dot-grid',
    name: 'Bullet Dot Grid 5mm',
    category: 'Backgrounds',
    type: 'pattern',
    url: 'dot-grid-5mm',
    tags: ['dots', 'journal', 'bujo', 'grid'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'bg-college-ruled',
    name: 'College Ruled Lines',
    category: 'Backgrounds',
    type: 'pattern',
    url: 'college-ruled',
    tags: ['lines', 'notebook', 'writing'],
    createdAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'bg-isometric-grid',
    name: 'Isometric Triangular Grid',
    category: 'Backgrounds',
    type: 'pattern',
    url: 'isometric-grid',
    tags: ['isometric', 'geometry', 'graph'],
    createdAt: '2026-08-01T00:00:00Z',
  },
];

export const DEMO_ASSETS = DEFAULT_ASSETS;
