import { BookTheme } from '../types/book';

export const BUILTIN_BOOK_THEMES: BookTheme[] = [
  {
    id: 'theme-clean-minimal',
    name: 'Minimal',
    description: 'Modern, high-legibility sans-serif pairing with fine geometric borders and airy negative space.',
    fontHeading: 'Outfit',
    fontBody: 'Plus Jakarta Sans',
    fontAccent: 'Outfit',
    headingSize: 22,
    bodySize: 13,
    primaryColor: '#111827',
    secondaryColor: '#4B5563',
    borderColor: '#E5E7EB',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 8,
    pageSpacing: 24,
    puzzleGridStyle: 'minimal',
  },
  {
    id: 'theme-classic-book',
    name: 'Classic',
    description: 'Timeless literary typography pairing serif chapter titles with warm editorial elegance.',
    fontHeading: 'Cinzel',
    fontBody: 'Merriweather',
    fontAccent: 'Cinzel',
    headingSize: 26,
    bodySize: 13,
    primaryColor: '#1C1917',
    secondaryColor: '#57534E',
    borderColor: '#D6D3D1',
    borderStyle: 'double',
    borderWidth: 2,
    borderRadius: 0,
    pageSpacing: 28,
    puzzleGridStyle: 'classic',
  },
  {
    id: 'theme-modern-puzzle',
    name: 'Modern',
    description: 'Crisp geometric display typography with high-contrast rules and contemporary layout accents.',
    fontHeading: 'Space Grotesk',
    fontBody: 'Plus Jakarta Sans',
    fontAccent: 'Space Grotesk',
    headingSize: 24,
    bodySize: 14,
    primaryColor: '#0F172A',
    secondaryColor: '#334155',
    borderColor: '#CBD5E1',
    borderStyle: 'solid',
    borderWidth: 1.5,
    borderRadius: 12,
    pageSpacing: 22,
    puzzleGridStyle: 'clean',
  },
  {
    id: 'theme-large-print',
    name: 'Large Print (Senior Friendly)',
    description: 'Generous 18pt–22pt text sizing with ultra high contrast and extra wide spacing for seniors & low vision readers.',
    fontHeading: 'Outfit',
    fontBody: 'Plus Jakarta Sans',
    fontAccent: 'Outfit',
    headingSize: 30,
    bodySize: 18,
    primaryColor: '#000000',
    secondaryColor: '#1F2937',
    borderColor: '#111827',
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 8,
    pageSpacing: 32,
    puzzleGridStyle: 'bold',
  },
  {
    id: 'theme-kids-activity',
    name: 'Kids',
    description: 'Playful, high-readability rounded typography with soft borders and spacious interaction zones.',
    fontHeading: 'Quicksand',
    fontBody: 'Poppins',
    fontAccent: 'Quicksand',
    headingSize: 28,
    bodySize: 15,
    primaryColor: '#1E1B4B',
    secondaryColor: '#4338CA',
    borderColor: '#818CF8',
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 16,
    pageSpacing: 20,
    puzzleGridStyle: 'playful',
  },
  {
    id: 'theme-professional-kdp',
    name: 'Professional',
    description: 'Executive publishing aesthetic with refined proportions, balanced gutters, and crisp line hierarchy.',
    fontHeading: 'Inter',
    fontBody: 'Plus Jakarta Sans',
    fontAccent: 'Inter',
    headingSize: 24,
    bodySize: 14,
    primaryColor: '#09090B',
    secondaryColor: '#3F3F46',
    borderColor: '#E4E4E7',
    borderStyle: 'solid',
    borderWidth: 1.5,
    borderRadius: 4,
    pageSpacing: 26,
    puzzleGridStyle: 'clean',
  },
  {
    id: 'theme-academic',
    name: 'Academic & Logic',
    description: 'Structured slab-serif headers with precise typographic hierarchy and rigorous grid dividers.',
    fontHeading: 'Bitter',
    fontBody: 'Inter',
    fontAccent: 'Bitter',
    headingSize: 22,
    bodySize: 13,
    primaryColor: '#18181B',
    secondaryColor: '#52525B',
    borderColor: '#A1A1AA',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 4,
    pageSpacing: 24,
    puzzleGridStyle: 'bold',
  },
  {
    id: 'theme-bold-puzzle',
    name: 'Bold Impact',
    description: 'Heavyweight impactful display headings paired with high-contrast puzzle grid line weights.',
    fontHeading: 'Montserrat',
    fontBody: 'Plus Jakarta Sans',
    fontAccent: 'Montserrat',
    headingSize: 26,
    bodySize: 14,
    primaryColor: '#000000',
    secondaryColor: '#27272A',
    borderColor: '#18181B',
    borderStyle: 'solid',
    borderWidth: 2.5,
    borderRadius: 6,
    pageSpacing: 20,
    puzzleGridStyle: 'bold',
  },
  {
    id: 'theme-botanical-floral',
    name: 'Floral & Botanical',
    description: 'Delicate serif styling with organic balance and soft refined framing rules for cozy puzzle books.',
    fontHeading: 'Playfair Display',
    fontBody: 'Plus Jakarta Sans',
    fontAccent: 'Playfair Display',
    headingSize: 25,
    bodySize: 13,
    primaryColor: '#1C1917',
    secondaryColor: '#44403C',
    borderColor: '#D6D3D1',
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 12,
    pageSpacing: 26,
    puzzleGridStyle: 'minimal',
  },
  {
    id: 'theme-blueprint-tech',
    name: 'Blueprint & Logic',
    description: 'Precise mono-inspired grid typography with crisp architectural lines for serious puzzle enthusiasts.',
    fontHeading: 'Space Grotesk',
    fontBody: 'Inter',
    fontAccent: 'Space Grotesk',
    headingSize: 22,
    bodySize: 12,
    primaryColor: '#0F172A',
    secondaryColor: '#334155',
    borderColor: '#64748B',
    borderStyle: 'solid',
    borderWidth: 1.5,
    borderRadius: 2,
    pageSpacing: 22,
    puzzleGridStyle: 'clean',
  },
  {
    id: 'theme-vintage-editorial',
    name: 'Vintage Editorial',
    description: 'Classic newspaper and period publication styling with prominent headers and double rule separators.',
    fontHeading: 'Merriweather',
    fontBody: 'Merriweather',
    fontAccent: 'Cinzel',
    headingSize: 24,
    bodySize: 13,
    primaryColor: '#18181B',
    secondaryColor: '#3F3F46',
    borderColor: '#71717A',
    borderStyle: 'double',
    borderWidth: 2,
    borderRadius: 0,
    pageSpacing: 26,
    puzzleGridStyle: 'classic',
  },
  {
    id: 'theme-junior-fun',
    name: 'Junior Explorer',
    description: 'Friendly, extra-large fonts with soft bubble corners designed for young puzzle solvers aged 6–12.',
    fontHeading: 'Quicksand',
    fontBody: 'Poppins',
    fontAccent: 'Quicksand',
    headingSize: 30,
    bodySize: 16,
    primaryColor: '#0C4A6E',
    secondaryColor: '#0369A1',
    borderColor: '#38BDF8',
    borderStyle: 'solid',
    borderWidth: 2,
    borderRadius: 18,
    pageSpacing: 22,
    puzzleGridStyle: 'playful',
  },
];

export const DEFAULT_BOOK_THEME = BUILTIN_BOOK_THEMES[0];
