import { DocumentModel, Project } from '../types';
import { calculateKdpCoverDimensions, calculateKdpSpineWidth, STANDARD_TRIM_SIZES } from './kdp';

const trim6x9 = STANDARD_TRIM_SIZES.find(t => t.id === '6x9')!;
const trim85x11 = STANDARD_TRIM_SIZES.find(t => t.id === '8.5x11')!;

const spine6x9_80 = calculateKdpSpineWidth(80, 'White');
const cover6x9_80 = calculateKdpCoverDimensions(6, 9, spine6x9_80);

const spine85x11_100 = calculateKdpSpineWidth(100, 'White');
const cover85x11_100 = calculateKdpCoverDimensions(8.5, 11, spine85x11_100);

const spine85x11_60 = calculateKdpSpineWidth(60, 'White');
const cover85x11_60 = calculateKdpCoverDimensions(8.5, 11, spine85x11_60);

const spine85x11_80 = calculateKdpSpineWidth(80, 'White');
const cover85x11_80 = calculateKdpCoverDimensions(8.5, 11, spine85x11_80);

export const INITIAL_DEMO_PROJECTS: { project: Project; document: DocumentModel }[] = [
  {
    project: {
      id: 'proj-wonders-ws',
      name: 'Global Wonders Word Search',
      type: 'Puzzle Book',
      description: '80 curated large-print word search puzzles exploring ancient world wonders, famous landmarks, cultural monuments, and modern architectural marvels.',
      thumbnail: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=400&auto=format&fit=crop&q=80',
      pageCount: 80,
      createdAt: '2026-08-18T09:00:00Z',
      updatedAt: '2026-08-22T10:00:00Z',
      status: 'Completed',
      ownerId: 'user-default-1',
      isFavorite: true,
      documentId: 'doc-wonders-ws',
      kdpSettings: {
        trimSize: trim85x11,
        orientation: 'Portrait',
        pageCount: 80,
        margins: { top: 0.5, bottom: 0.5, left: 0.75, right: 0.5 },
        bleed: 'No Bleed',
        paperType: 'White',
        spineWidthInches: spine85x11_80,
        coverWidthInches: cover85x11_80.width,
        coverHeightInches: cover85x11_80.height,
      },
      metadata: {
        category: 'Puzzles & Games',
        targetAudience: 'Adults & Seniors',
        keywords: ['word search', 'wonders of the world', 'large print', 'travel landmarks', 'brain games'],
        coverColor: '#0F172A',
        author: 'Global Wonders Studio',
        subtitle: '80 Large Print Themed Puzzles for Travelers & Puzzle Lovers',
        language: 'English',
      },
    },
    document: {
      id: 'doc-wonders-ws',
      projectId: 'proj-wonders-ws',
      createdAt: '2026-08-18T09:00:00Z',
      updatedAt: '2026-08-22T10:00:00Z',
      pages: [
        {
          id: 'page-wonders-1',
          pageNumber: 1,
          backgroundColor: '#FFFFFF',
          notes: 'Title & Copyright Page',
          elements: [
            {
              id: 'el-wonders-p1-title',
              type: 'text',
              content: 'GLOBAL WONDERS\nWORD SEARCH',
              x: 72,
              y: 220,
              width: 672,
              height: 160,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fontFamily: 'Noto Sans',
              fontSize: 34,
              fontWeight: '800',
              textAlign: 'center',
              color: '#0F172A',
              lineHeight: 1.2,
              letterSpacing: 2,
            },
            {
              id: 'el-wonders-p1-sub',
              type: 'text',
              content: '80 Large Print Themed Puzzles Exploring Wonders of the World',
              x: 72,
              y: 400,
              width: 672,
              height: 32,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fontFamily: 'Noto Sans',
              fontSize: 16,
              fontWeight: '500',
              textAlign: 'center',
              color: '#475569',
              lineHeight: 1.2,
              letterSpacing: 0.5,
            },
            {
              id: 'el-wonders-p1-divider',
              type: 'line',
              strokeColor: '#0F172A',
              strokeWidth: 2,
              lineStyle: 'solid',
              x: 288,
              y: 385,
              width: 240,
              height: 2,
              rotation: 0,
              zIndex: 1,
              opacity: 0.8,
            },
          ],
        },
        {
          id: 'page-wonders-2',
          pageNumber: 2,
          backgroundColor: '#FFFFFF',
          notes: 'Puzzle 01: Seven Wonders of the World',
          elements: [
            {
              id: 'el-wonders-p2-head',
              type: 'text',
              content: 'PUZZLE 01 • SEVEN WONDERS OF THE ANCIENT & MODERN WORLD',
              x: 72,
              y: 42,
              width: 672,
              height: 44,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fontFamily: 'Outfit',
              fontSize: 32,
              fontWeight: '700',
              textAlign: 'center',
              color: '#0F172A',
              lineHeight: 1.2,
              letterSpacing: 1.5,
            },
            {
              id: 'el-wonders-p2-puzzle',
              type: 'puzzle',
              puzzleType: 'word_search',
              difficulty: 'Medium',
              title: 'Wonders of the World',
              x: 72,
              y: 96,
              width: 672,
              height: 824,
              rotation: 0,
              zIndex: 2,
              opacity: 1,
              puzzleData: {
                title: 'Wonders of the World',
                type: 'word_search',
                difficulty: 'Medium',
                settings: {
                  gridSize: 14,
                  wordListPosition: 'bottom',
                  wordListColumns: 3,
                },
                data: {
                  grid: [
                    ['C', 'O', 'L', 'O', 'S', 'S', 'E', 'U', 'M', 'P', 'E', 'T', 'R', 'A'],
                    ['H', 'I', 'P', 'Y', 'R', 'A', 'M', 'I', 'D', 'S', 'A', 'K', 'T', 'G'],
                    ['I', 'C', 'H', 'E', 'N', 'I', 'T', 'Z', 'A', 'M', 'J', 'E', 'A', 'R'],
                    ['C', 'T', 'A', 'J', 'M', 'A', 'H', 'A', 'L', 'O', 'H', 'P', 'J', 'E'],
                    ['H', 'M', 'A', 'C', 'H', 'U', 'P', 'I', 'C', 'C', 'H', 'U', 'M', 'A'],
                    ['E', 'A', 'N', 'G', 'K', 'O', 'R', 'W', 'A', 'T', 'B', 'A', 'A', 'T'],
                    ['N', 'P', 'A', 'R', 'T', 'H', 'E', 'N', 'O', 'N', 'O', 'L', 'H', 'W'],
                    ['I', 'C', 'H', 'R', 'I', 'S', 'T', 'R', 'E', 'D', 'E', 'E', 'A', 'A'],
                    ['T', 'S', 'T', 'O', 'N', 'E', 'H', 'E', 'N', 'G', 'E', 'R', 'L', 'L'],
                    ['Z', 'E', 'P', 'H', 'E', 'S', 'U', 'S', 'G', 'I', 'Z', 'A', 'L', 'L'],
                    ['A', 'C', 'A', 'R', 'N', 'A', 'C', 'L', 'U', 'X', 'O', 'R', 'W', 'P'],
                    ['A', 'L', 'H', 'A', 'M', 'B', 'R', 'A', 'A', 'C', 'R', 'O', 'P', 'O'],
                    ['P', 'A', 'L', 'M', 'Y', 'R', 'A', 'B', 'O', 'R', 'O', 'B', 'U', 'D'],
                    ['S', 'A', 'G', 'R', 'A', 'D', 'A', 'F', 'A', 'M', 'I', 'L', 'I', 'A'],
                  ],
                  words: [
                    'COLOSSEUM',
                    'PETRA',
                    'PYRAMIDS',
                    'TAJ MAHAL',
                    'MACHU PICCHU',
                    'ANGKOR WAT',
                    'PARTHENON',
                    'STONEHENGE',
                    'ALHAMBRA',
                    'GREAT WALL',
                    'CHICHEN ITZA',
                    'CHRIST REDEEMER',
                  ],
                },
                previewData: {
                  clueFontSize: 26,
                  gridFontSize: 40,
                  titleFontSize: 32,
                  fontFamily: 'Plus Jakarta Sans',
                },
              },
            },
          ],
        },
      ],
    },
  },
  {
    project: {
      id: 'proj-animals-ws',
      name: 'Animals Word Search Book',
      type: 'Puzzle Book',
      description: '80 curated large-print word search puzzles exploring wildlife, sea creatures, safari animals, and rainforest habitats.',
      thumbnail: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=400&auto=format&fit=crop&q=80',
      pageCount: 80,
      createdAt: '2026-08-10T10:30:00Z',
      updatedAt: '2026-08-16T11:15:00Z',
      status: 'In Progress',
      ownerId: 'user-default-1',
      isFavorite: true,
      documentId: 'doc-animals-ws',
      kdpSettings: {
        trimSize: trim6x9,
        orientation: 'Portrait',
        pageCount: 80,
        margins: { top: 0.5, bottom: 0.5, left: 0.5, right: 0.375 },
        bleed: 'No Bleed',
        paperType: 'White',
        spineWidthInches: spine6x9_80,
        coverWidthInches: cover6x9_80.width,
        coverHeightInches: cover6x9_80.height,
      },
      metadata: {
        category: 'Puzzles & Games',
        targetAudience: 'Adults & Seniors',
        keywords: ['word search', 'animals puzzle', 'large print', 'wildlife brain games'],
        coverColor: '#059669',
      },
    },
    document: {
      id: 'doc-animals-ws',
      projectId: 'proj-animals-ws',
      createdAt: '2026-08-10T10:30:00Z',
      updatedAt: '2026-08-16T11:15:00Z',
      pages: [
        {
          id: 'page-ws-1',
          pageNumber: 1,
          backgroundColor: '#FFFFFF',
          notes: 'Title & Copyright Page',
          elements: [
            {
              id: 'el-p1-title',
              type: 'text',
              content: 'THE ULTIMATE\nANIMALS\nWORD SEARCH',
              x: 50,
              y: 200,
              width: 476,
              height: 150,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fontFamily: 'Outfit',
              fontSize: 32,
              fontWeight: '800',
              textAlign: 'center',
              color: '#064E3B',
              lineHeight: 1.2,
              letterSpacing: 2,
            },
            {
              id: 'el-p1-sub',
              type: 'text',
              content: '80 Large Print Themed Puzzles for Animal Lovers',
              x: 50,
              y: 380,
              width: 476,
              height: 30,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fontFamily: 'Plus Jakarta Sans',
              fontSize: 14,
              fontWeight: '500',
              textAlign: 'center',
              color: '#4B5563',
              lineHeight: 1,
              letterSpacing: 0.5,
            },
            {
              id: 'el-p1-divider',
              type: 'line',
              strokeColor: '#059669',
              strokeWidth: 2,
              lineStyle: 'solid',
              x: 188,
              y: 360,
              width: 200,
              height: 2,
              rotation: 0,
              zIndex: 1,
              opacity: 0.8,
            },
          ],
        },
        {
          id: 'page-ws-2',
          pageNumber: 2,
          backgroundColor: '#FFFFFF',
          notes: 'Puzzle 1: Safari Wildlife',
          elements: [
            {
              id: 'el-p2-head',
              type: 'text',
              content: 'PUZZLE 01 • AFRICAN SAFARI',
              x: 50,
              y: 35,
              width: 476,
              height: 42,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fontFamily: 'Outfit',
              fontSize: 32,
              fontWeight: '700',
              textAlign: 'center',
              color: '#111827',
              lineHeight: 1.2,
              letterSpacing: 1.5,
            },
            {
              id: 'el-p2-border',
              type: 'shape',
              shapeType: 'rectangle',
              x: 65,
              y: 85,
              width: 446,
              height: 446,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fillColor: 'transparent',
              strokeColor: '#064E3B',
              strokeWidth: 2,
              borderRadius: 4,
            },
            {
              id: 'el-p2-puzzle',
              type: 'puzzle',
              puzzleType: 'Word Search',
              difficulty: 'Medium',
              title: 'African Safari',
              gridSize: 15,
              wordCount: 12,
              x: 88,
              y: 108,
              width: 400,
              height: 400,
              rotation: 0,
              zIndex: 2,
              opacity: 1,
            },
            {
              id: 'el-p2-words-title',
              type: 'text',
              content: 'FIND THE 12 HIDDEN SAFARI WORDS:',
              x: 65,
              y: 545,
              width: 446,
              height: 34,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fontFamily: 'Plus Jakarta Sans',
              fontSize: 28,
              fontWeight: '700',
              textAlign: 'center',
              color: '#374151',
              lineHeight: 1.2,
              letterSpacing: 1,
            },
            {
              id: 'el-p2-words',
              type: 'text',
              content: 'CHEETAH • ELEPHANT • GIRAFFE • GAZELLE\nHIPPO • HYENA • LEOPARD • LION\nMEERKAT • OSTRICH • RHINO • ZEBRA',
              x: 65,
              y: 585,
              width: 446,
              height: 80,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fontFamily: 'Plus Jakarta Sans',
              fontSize: 26,
              fontWeight: '500',
              textAlign: 'center',
              color: '#1F2937',
              lineHeight: 1.6,
              letterSpacing: 0.5,
            },
          ],
        },
      ],
    },
  },
  {
    project: {
      id: 'proj-sudoku-adults',
      name: 'Easy Sudoku for Adults',
      type: 'Puzzle Book',
      description: '100 accessible 9x9 Sudoku puzzles crafted with high-visibility large numbers and gentle difficulty progression.',
      thumbnail: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&auto=format&fit=crop&q=80',
      pageCount: 100,
      createdAt: '2026-08-11T14:00:00Z',
      updatedAt: '2026-08-15T09:20:00Z',
      status: 'Completed',
      ownerId: 'user-default-1',
      isFavorite: false,
      documentId: 'doc-sudoku-adults',
      kdpSettings: {
        trimSize: trim85x11,
        orientation: 'Portrait',
        pageCount: 100,
        margins: { top: 0.5, bottom: 0.5, left: 0.5, right: 0.375 },
        bleed: 'No Bleed',
        paperType: 'White',
        spineWidthInches: spine85x11_100,
        coverWidthInches: cover85x11_100.width,
        coverHeightInches: cover85x11_100.height,
      },
      metadata: {
        category: 'Sudoku',
        targetAudience: 'Adults & Beginners',
        keywords: ['easy sudoku', 'number puzzle', 'cognitive training', 'relaxation'],
        coverColor: '#2563EB',
      },
    },
    document: {
      id: 'doc-sudoku-adults',
      projectId: 'proj-sudoku-adults',
      createdAt: '2026-08-11T14:00:00Z',
      updatedAt: '2026-08-15T09:20:00Z',
      pages: [
        {
          id: 'page-sudoku-1',
          pageNumber: 1,
          backgroundColor: '#FFFFFF',
          notes: 'How to play & Puzzle 1',
          elements: [
            {
              id: 'el-sdk-title',
              type: 'text',
              content: 'EASY SUDOKU • PUZZLE #01',
              x: 60,
              y: 50,
              width: 700,
              height: 36,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fontFamily: 'Outfit',
              fontSize: 22,
              fontWeight: '700',
              textAlign: 'center',
              color: '#1E3A8A',
              lineHeight: 1.2,
              letterSpacing: 1.5,
            },
            {
              id: 'el-sdk-box',
              type: 'shape',
              shapeType: 'rectangle',
              x: 170,
              y: 120,
              width: 480,
              height: 480,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fillColor: 'transparent',
              strokeColor: '#1E3A8A',
              strokeWidth: 3,
              borderRadius: 4,
            },
            {
              id: 'el-sdk-instructions',
              type: 'text',
              content: 'Rule: Fill every row, column, and 3×3 box with numbers from 1 to 9 without repetition.',
              x: 60,
              y: 640,
              width: 700,
              height: 24,
              rotation: 0,
              zIndex: 1,
              opacity: 0.8,
              fontFamily: 'Plus Jakarta Sans',
              fontSize: 13,
              fontWeight: '500',
              textAlign: 'center',
              color: '#4B5563',
              lineHeight: 1,
              letterSpacing: 0,
            },
          ],
        },
      ],
    },
  },
  {
    project: {
      id: 'proj-cute-animals-cb',
      name: 'Cute Animals Coloring Book',
      type: 'Coloring Book',
      description: '50 bold line art coloring illustrations featuring playful kittens, woodland creatures, and cute puppies for all ages.',
      thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=400&auto=format&fit=crop&q=80',
      pageCount: 50,
      createdAt: '2026-08-12T16:00:00Z',
      updatedAt: '2026-08-16T12:00:00Z',
      status: 'Draft',
      ownerId: 'user-default-1',
      isFavorite: true,
      documentId: 'doc-cute-animals-cb',
      kdpSettings: {
        trimSize: trim85x11,
        orientation: 'Portrait',
        pageCount: 50,
        margins: { top: 0.5, bottom: 0.5, left: 0.5, right: 0.375 },
        bleed: 'Bleed',
        paperType: 'White',
        spineWidthInches: spine85x11_60,
        coverWidthInches: cover85x11_60.width,
        coverHeightInches: cover85x11_60.height,
      },
      metadata: {
        category: 'Coloring Books',
        targetAudience: 'Kids & Teens',
        keywords: ['coloring book', 'cute animals', 'bold lines', 'mindfulness art'],
        coverColor: '#EC4899',
      },
    },
    document: {
      id: 'doc-cute-animals-cb',
      projectId: 'proj-cute-animals-cb',
      createdAt: '2026-08-12T16:00:00Z',
      updatedAt: '2026-08-16T12:00:00Z',
      pages: [
        {
          id: 'page-cb-1',
          pageNumber: 1,
          backgroundColor: '#FFFFFF',
          notes: 'Coloring Page 1',
          elements: [
            {
              id: 'el-cb-border',
              type: 'shape',
              shapeType: 'rectangle',
              x: 50,
              y: 50,
              width: 720,
              height: 950,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fillColor: 'transparent',
              strokeColor: '#18181B',
              strokeWidth: 3,
              borderRadius: 6,
            },
            {
              id: 'el-cb-header',
              type: 'text',
              content: 'BE CURIOUS & KIND',
              x: 100,
              y: 100,
              width: 620,
              height: 48,
              rotation: 0,
              zIndex: 2,
              opacity: 1,
              fontFamily: 'Outfit',
              fontSize: 32,
              fontWeight: '800',
              textAlign: 'center',
              color: '#18181B',
              lineHeight: 1.2,
              letterSpacing: 4,
            },
            {
              id: 'el-cb-circle',
              type: 'shape',
              shapeType: 'circle',
              x: 210,
              y: 300,
              width: 400,
              height: 400,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fillColor: 'transparent',
              strokeColor: '#18181B',
              strokeWidth: 3,
            },
          ],
        },
      ],
    },
  },
  {
    project: {
      id: 'proj-daily-planner-2026',
      name: 'Daily Planner 2026',
      type: 'Planner',
      description: 'Complete quarterly productivity layout with morning intentions, hourly appointment blocks, and evening reflection.',
      thumbnail: 'https://images.unsplash.com/photo-1506784365847-bbad939e9335?w=400&auto=format&fit=crop&q=80',
      pageCount: 120,
      createdAt: '2026-08-08T08:00:00Z',
      updatedAt: '2026-08-14T15:40:00Z',
      status: 'In Progress',
      ownerId: 'user-default-1',
      isFavorite: false,
      documentId: 'doc-daily-planner-2026',
      kdpSettings: {
        trimSize: trim85x11,
        orientation: 'Portrait',
        pageCount: 120,
        margins: { top: 0.5, bottom: 0.5, left: 0.5, right: 0.375 },
        bleed: 'No Bleed',
        paperType: 'Cream',
        spineWidthInches: spine85x11_100,
        coverWidthInches: cover85x11_100.width,
        coverHeightInches: cover85x11_100.height,
      },
      metadata: {
        category: 'Planners & Organizers',
        targetAudience: 'Professionals & Students',
        keywords: ['daily planner 2026', 'productivity journal', 'time blocking'],
        coverColor: '#D97706',
      },
    },
    document: {
      id: 'doc-daily-planner-2026',
      projectId: 'proj-daily-planner-2026',
      createdAt: '2026-08-08T08:00:00Z',
      updatedAt: '2026-08-14T15:40:00Z',
      pages: [
        {
          id: 'page-dp-1',
          pageNumber: 1,
          backgroundColor: '#FFFFFF',
          notes: 'Daily Spread',
          elements: [
            {
              id: 'el-dp-head',
              type: 'text',
              content: 'DAY OVERVIEW',
              x: 60,
              y: 50,
              width: 300,
              height: 32,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fontFamily: 'Outfit',
              fontSize: 20,
              fontWeight: '700',
              textAlign: 'left',
              color: '#111827',
              lineHeight: 1,
              letterSpacing: 1,
            },
          ],
        },
      ],
    },
  },
  {
    project: {
      id: 'proj-kids-activity-maze',
      name: 'Kids Activity Book',
      type: 'Activity Book',
      description: 'Labyrinths, spot the difference challenges, dot-to-dot drawings, and word scrambles for ages 6-10.',
      thumbnail: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&auto=format&fit=crop&q=80',
      pageCount: 60,
      createdAt: '2026-08-13T11:00:00Z',
      updatedAt: '2026-08-16T08:30:00Z',
      status: 'Draft',
      ownerId: 'user-default-1',
      isFavorite: true,
      documentId: 'doc-kids-activity-maze',
      kdpSettings: {
        trimSize: trim85x11,
        orientation: 'Portrait',
        pageCount: 60,
        margins: { top: 0.5, bottom: 0.5, left: 0.5, right: 0.375 },
        bleed: 'No Bleed',
        paperType: 'White',
        spineWidthInches: spine85x11_60,
        coverWidthInches: cover85x11_60.width,
        coverHeightInches: cover85x11_60.height,
      },
      metadata: {
        category: 'Children Activity',
        targetAudience: 'Kids 6-10',
        keywords: ['kids activity book', 'mazes', 'brain teasers', 'fun puzzles'],
        coverColor: '#8B5CF6',
      },
    },
    document: {
      id: 'doc-kids-activity-maze',
      projectId: 'proj-kids-activity-maze',
      createdAt: '2026-08-13T11:00:00Z',
      updatedAt: '2026-08-16T08:30:00Z',
      pages: [
        {
          id: 'page-ka-1',
          pageNumber: 1,
          backgroundColor: '#FFFFFF',
          notes: 'Maze Challenge',
          elements: [
            {
              id: 'el-ka-title',
              type: 'text',
              content: 'SPACE ADVENTURE MAZE',
              x: 60,
              y: 50,
              width: 700,
              height: 36,
              rotation: 0,
              zIndex: 1,
              opacity: 1,
              fontFamily: 'Outfit',
              fontSize: 22,
              fontWeight: '800',
              textAlign: 'center',
              color: '#4338CA',
              lineHeight: 1.2,
              letterSpacing: 2,
            },
          ],
        },
      ],
    },
  },
];
