import { PuzzleTypeInfo } from '../types';

export const PUZZLE_TYPES: { id: string; name: string; description: string; icon: string }[] = [
  { id: 'word_search', name: 'Word Search', description: 'Search letters grid with custom word list', icon: 'Grid3X3' },
  { id: 'sudoku', name: 'Sudoku 9×9', description: 'Classic number logic with unique solutions', icon: 'Hash' },
  { id: 'crossword', name: 'Crossword', description: 'Interlocking clue matrix and vocabulary', icon: 'Table' },
  { id: 'maze', name: 'Maze Labyrinth', description: 'Pathfinding maze with start & exit paths', icon: 'Compass' },
  { id: 'cryptogram', name: 'Cryptogram', description: 'Encrypted cypher quotes and phrases', icon: 'Lock' },
  { id: 'word_scramble', name: 'Word Scramble', description: 'Jumbled anagrams and vocab puzzles', icon: 'Type' },
  { id: 'number_puzzle', name: 'Number Puzzle', description: 'Math cross and Kakuro number grids', icon: 'Binary' },
  { id: 'logic_grid', name: 'Logic Grid', description: 'Deductive reasoning matching matrices', icon: 'Layers' },
];

export const PUZZLE_TYPES_INFO: PuzzleTypeInfo[] = [
  {
    type: 'Word Search',
    title: 'Word Search Generator',
    description: 'Custom grids with horizontal, vertical, diagonal, and backwards word placements, custom word banks, and solution keys.',
    iconName: 'Search',
    difficultyOptions: ['Easy', 'Medium', 'Hard', 'Expert'],
    defaultGridSize: '15 × 15',
    popularFor: 'Themed vocabulary books, senior activity books, kids learning',
    samplePreview: 'W O R D S E A R C H',
  },
  {
    type: 'Sudoku',
    title: 'Sudoku Generator',
    description: 'Classic 9x9, 6x6, and 4x4 symmetrical Sudoku puzzles with guaranteed unique solutions and graded difficulty algorithms.',
    iconName: 'Grid3X3',
    difficultyOptions: ['Easy', 'Medium', 'Hard', 'Expert'],
    defaultGridSize: '9 × 9',
    popularFor: 'Classic number puzzle books, travel paperbacks, daily challenges',
    samplePreview: '5 3 . | . 7 . | . . .',
  },
  {
    type: 'Crossword',
    title: 'Crossword Generator',
    description: 'High-density crossword layouts with across & down numbered clue generation, custom themes, and clean print typography.',
    iconName: 'LayoutGrid',
    difficultyOptions: ['Easy', 'Medium', 'Hard'],
    defaultGridSize: '13 × 13',
    popularFor: 'General trivia books, educational workbooks, newspaper styles',
    samplePreview: '1. [A] [P] [P] [L] [E]',
  },
  {
    type: 'Maze',
    title: 'Maze Generator',
    description: 'Algorithmic maze generation (DFS, Prim, Kruskal) in square, circular, hexagonal, and custom mask shapes with path solutions.',
    iconName: 'Compass',
    difficultyOptions: ['Easy', 'Medium', 'Hard', 'Expert'],
    defaultGridSize: '25 × 25',
    popularFor: 'Kids adventure books, adult relaxing labyrinth books',
    samplePreview: '[START] ══╗ ║ ╚══ [FINISH]',
  },
  {
    type: 'Cryptogram',
    title: 'Cryptogram & Cipher',
    description: 'Encrypted famous quotes, inspirational sayings, and historical passages with letter substitution cyphers and hint tables.',
    iconName: 'KeyRound',
    difficultyOptions: ['Easy', 'Medium', 'Hard'],
    defaultGridSize: 'Letter Substitution',
    popularFor: 'Adult brain teasers, mystery lover books, quote collections',
    samplePreview: 'A=X, B=Q, C=M...',
  },
  {
    type: 'Word Scramble',
    title: 'Word Scramble',
    description: 'Jumbled vocabulary challenge creator with hint anagrams, category tags, and organized answer key layouts.',
    iconName: 'Shuffle',
    difficultyOptions: ['Easy', 'Medium', 'Hard'],
    defaultGridSize: 'List layout',
    popularFor: 'Elementary school activity books, ESL workbooks, party games',
    samplePreview: 'E P L P A → APPLE',
  },
  {
    type: 'Number Puzzle',
    title: 'Number Cross & Kakuro',
    description: 'Mathematical grid puzzles including Kakuro, Number Search, and Math Crossword challenges with step-by-step solutions.',
    iconName: 'Binary',
    difficultyOptions: ['Easy', 'Medium', 'Hard', 'Expert'],
    defaultGridSize: '10 × 10',
    popularFor: 'Math lovers, STEM puzzle collections, cognitive training',
    samplePreview: '[16\\] = 9 + 7',
  },
  {
    type: 'Logic Puzzle',
    title: 'Logic Grid & Nonogram',
    description: 'Deductive reasoning grid puzzles, picture-logic nonograms, and matching matrices with full solution verification.',
    iconName: 'Brain',
    difficultyOptions: ['Easy', 'Medium', 'Hard'],
    defaultGridSize: '5 × 5 Matrix',
    popularFor: 'Detective logic books, IQ workout workbooks, escape books',
    samplePreview: 'Person A | Red Car | Monday',
  },
];
