import { Template } from '../types';
import { STANDARD_TRIM_SIZES } from './kdp';

const trim6x9 = STANDARD_TRIM_SIZES.find(t => t.id === '6x9')!;
const trim85x11 = STANDARD_TRIM_SIZES.find(t => t.id === '8.5x11')!;
const trim8x10 = STANDARD_TRIM_SIZES.find(t => t.id === '8x10')!;

export const DEMO_TEMPLATES: Template[] = [
  {
    id: 'tmpl-word-search-classic',
    name: 'Classic Word Search 15x15',
    category: 'Puzzle Books',
    projectType: 'Puzzle Book',
    thumbnail: 'https://images.unsplash.com/photo-1585776245991-cf89dd7fc73a?w=400&auto=format&fit=crop&q=80',
    description: 'Clean KDP-ready word search interior with uppercase 15x15 letter grid, word bank container, and puzzle title header.',
    pageSize: trim6x9,
    orientation: 'Portrait',
    pageCount: 60,
    tags: ['puzzles', 'word search', '6x9', 'adults'],
    isPopular: true,
    difficulty: 'Intermediate',
    pages: [
      {
        pageNumber: 1,
        backgroundColor: '#FFFFFF',
        elements: [
          {
            id: 'ws-title-1',
            type: 'text',
            content: 'PUZZLE 01 • WILD ANIMALS',
            x: 50,
            y: 40,
            width: 476,
            height: 40,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 20,
            fontWeight: '700',
            textAlign: 'center',
            color: '#111827',
            lineHeight: 1.2,
            letterSpacing: 2,
          },
          {
            id: 'ws-grid-box',
            type: 'shape',
            shapeType: 'rectangle',
            x: 75,
            y: 95,
            width: 426,
            height: 426,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: 'transparent',
            strokeColor: '#374151',
            strokeWidth: 2,
            borderRadius: 4,
          },
          {
            id: 'ws-puzzle-element',
            type: 'puzzle',
            puzzleType: 'Word Search',
            difficulty: 'Medium',
            title: 'Wild Animals',
            gridSize: 15,
            wordCount: 12,
            x: 88,
            y: 108,
            width: 400,
            height: 400,
            rotation: 0,
            zIndex: 2,
            opacity: 1,
          },
          {
            id: 'ws-wordbank-header',
            type: 'text',
            content: 'FIND THESE WORDS:',
            x: 75,
            y: 545,
            width: 426,
            height: 24,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 13,
            fontWeight: '700',
            textAlign: 'center',
            color: '#4B5563',
            lineHeight: 1.2,
            letterSpacing: 1.5,
          },
          {
            id: 'ws-wordbank-content',
            type: 'text',
            content: 'CHETAH • ELEPHANT • GIRAFFE • GORILLA\nLEOPARD • LION • RHINOCEROS • ZEBRA\nKANGAROO • PANDA • TIGER • MEERKAT',
            x: 75,
            y: 575,
            width: 426,
            height: 70,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Plus Jakarta Sans',
            fontSize: 12,
            fontWeight: '600',
            textAlign: 'center',
            color: '#1F2937',
            lineHeight: 1.8,
            letterSpacing: 1,
          },
          {
            id: 'ws-page-footer',
            type: 'text',
            content: 'Page 1',
            x: 200,
            y: 780,
            width: 176,
            height: 20,
            rotation: 0,
            zIndex: 1,
            opacity: 0.6,
            fontFamily: 'Plus Jakarta Sans',
            fontSize: 11,
            fontWeight: '400',
            textAlign: 'center',
            color: '#6B7280',
            lineHeight: 1,
            letterSpacing: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'tmpl-daily-planner-minimal',
    name: 'Minimalist Daily Focus Planner',
    category: 'Planners',
    projectType: 'Planner',
    thumbnail: 'https://images.unsplash.com/photo-1506784365847-bbad939e9335?w=400&auto=format&fit=crop&q=80',
    description: 'Clean structured productivity layout with top 3 priorities, time blocking schedule, habit trackers, and notes section.',
    pageSize: trim85x11,
    orientation: 'Portrait',
    pageCount: 100,
    tags: ['planner', 'productivity', '8.5x11', 'daily'],
    isPopular: true,
    difficulty: 'Beginner',
    pages: [
      {
        pageNumber: 1,
        backgroundColor: '#FFFFFF',
        elements: [
          {
            id: 'dp-header-title',
            type: 'text',
            content: 'DAILY FOCUS & INTENTION',
            x: 60,
            y: 50,
            width: 400,
            height: 36,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 22,
            fontWeight: '700',
            textAlign: 'left',
            color: '#111827',
            lineHeight: 1.2,
            letterSpacing: 1,
          },
          {
            id: 'dp-date-line',
            type: 'text',
            content: 'DATE: __________________   DAY: M  T  W  T  F  S  S',
            x: 480,
            y: 58,
            width: 280,
            height: 24,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'JetBrains Mono',
            fontSize: 11,
            fontWeight: '500',
            textAlign: 'right',
            color: '#4B5563',
            lineHeight: 1,
            letterSpacing: 0.5,
          },
          {
            id: 'dp-top-priority-box',
            type: 'shape',
            shapeType: 'rectangle',
            x: 60,
            y: 100,
            width: 700,
            height: 110,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: '#F9FAFB',
            strokeColor: '#E5E7EB',
            strokeWidth: 1.5,
            borderRadius: 6,
          },
          {
            id: 'dp-priority-title',
            type: 'text',
            content: 'TOP 3 PRIORITIES TODAY',
            x: 80,
            y: 112,
            width: 300,
            height: 20,
            rotation: 0,
            zIndex: 2,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 12,
            fontWeight: '700',
            textAlign: 'left',
            color: '#374151',
            lineHeight: 1,
            letterSpacing: 1,
          },
          {
            id: 'dp-priority-items',
            type: 'text',
            content: '☐ 1. ___________________________________________________________________\n☐ 2. ___________________________________________________________________\n☐ 3. ___________________________________________________________________',
            x: 80,
            y: 140,
            width: 660,
            height: 60,
            rotation: 0,
            zIndex: 2,
            opacity: 1,
            fontFamily: 'Plus Jakarta Sans',
            fontSize: 13,
            fontWeight: '500',
            textAlign: 'left',
            color: '#1F2937',
            lineHeight: 1.6,
            letterSpacing: 0,
          },
          {
            id: 'dp-schedule-box',
            type: 'shape',
            shapeType: 'rectangle',
            x: 60,
            y: 225,
            width: 440,
            height: 480,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: '#FFFFFF',
            strokeColor: '#E5E7EB',
            strokeWidth: 1.5,
            borderRadius: 6,
          },
          {
            id: 'dp-schedule-title',
            type: 'text',
            content: 'HOURLY SCHEDULE & APPOINTMENTS',
            x: 80,
            y: 240,
            width: 400,
            height: 20,
            rotation: 0,
            zIndex: 2,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 12,
            fontWeight: '700',
            textAlign: 'left',
            color: '#374151',
            lineHeight: 1,
            letterSpacing: 1,
          },
          {
            id: 'dp-schedule-rows',
            type: 'text',
            content: '06:00 AM  | ___________________________________________\n07:00 AM  | ___________________________________________\n08:00 AM  | ___________________________________________\n09:00 AM  | ___________________________________________\n10:00 AM  | ___________________________________________\n11:00 AM  | ___________________________________________\n12:00 PM  | ___________________________________________\n01:00 PM  | ___________________________________________\n02:00 PM  | ___________________________________________\n03:00 PM  | ___________________________________________\n04:00 PM  | ___________________________________________\n05:00 PM  | ___________________________________________\n06:00 PM  | ___________________________________________\n07:00 PM  | ___________________________________________',
            x: 80,
            y: 270,
            width: 400,
            height: 410,
            rotation: 0,
            zIndex: 2,
            opacity: 1,
            fontFamily: 'JetBrains Mono',
            fontSize: 11,
            fontWeight: '400',
            textAlign: 'left',
            color: '#4B5563',
            lineHeight: 1.9,
            letterSpacing: 0,
          },
          {
            id: 'dp-side-notes-box',
            type: 'shape',
            shapeType: 'rectangle',
            x: 520,
            y: 225,
            width: 240,
            height: 480,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: '#F9FAFB',
            strokeColor: '#E5E7EB',
            strokeWidth: 1.5,
            borderRadius: 6,
          },
          {
            id: 'dp-side-notes-title',
            type: 'text',
            content: 'HABITS & WATER INTAKE',
            x: 535,
            y: 240,
            width: 210,
            height: 20,
            rotation: 0,
            zIndex: 2,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 12,
            fontWeight: '700',
            textAlign: 'left',
            color: '#374151',
            lineHeight: 1,
            letterSpacing: 1,
          },
          {
            id: 'dp-water-cups',
            type: 'text',
            content: 'Water: 💧 💧 💧 💧 💧 💧 💧 💧\n\nGratitude:\n_____________________________\n_____________________________\n\nTo Call / Email:\n☐ __________________________\n☐ __________________________\n☐ __________________________',
            x: 535,
            y: 270,
            width: 210,
            height: 400,
            rotation: 0,
            zIndex: 2,
            opacity: 1,
            fontFamily: 'Plus Jakarta Sans',
            fontSize: 12,
            fontWeight: '500',
            textAlign: 'left',
            color: '#374151',
            lineHeight: 1.7,
            letterSpacing: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'tmpl-sudoku-4up-classic',
    name: 'Sudoku 4-Per-Page Master',
    category: 'Puzzle Books',
    projectType: 'Puzzle Book',
    thumbnail: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&auto=format&fit=crop&q=80',
    description: 'High-density 8.5x11 4-grid Sudoku layout optimized for adult puzzle paperbacks with clean difficulty badges.',
    pageSize: trim85x11,
    orientation: 'Portrait',
    pageCount: 120,
    tags: ['sudoku', 'puzzles', '8.5x11', 'large print'],
    isPopular: true,
    difficulty: 'Hard',
    pages: [
      {
        pageNumber: 1,
        backgroundColor: '#FFFFFF',
        elements: [
          {
            id: 'sudoku-main-title',
            type: 'text',
            content: 'SUDOKU CHALLENGE • MEDIUM LEVEL',
            x: 60,
            y: 40,
            width: 700,
            height: 32,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 18,
            fontWeight: '700',
            textAlign: 'center',
            color: '#111827',
            lineHeight: 1.2,
            letterSpacing: 2,
          },
          // Grid 1 Top-Left
          {
            id: 'sudoku-g1-title',
            type: 'text',
            content: 'Puzzle #01',
            x: 80,
            y: 85,
            width: 300,
            height: 20,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 13,
            fontWeight: '600',
            textAlign: 'center',
            color: '#374151',
            lineHeight: 1,
            letterSpacing: 1,
          },
          {
            id: 'sudoku-g1-box',
            type: 'shape',
            shapeType: 'rectangle',
            x: 95,
            y: 110,
            width: 270,
            height: 270,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: 'transparent',
            strokeColor: '#1F2937',
            strokeWidth: 2,
            borderRadius: 2,
          },
          // Grid 2 Top-Right
          {
            id: 'sudoku-g2-title',
            type: 'text',
            content: 'Puzzle #02',
            x: 440,
            y: 85,
            width: 300,
            height: 20,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 13,
            fontWeight: '600',
            textAlign: 'center',
            color: '#374151',
            lineHeight: 1,
            letterSpacing: 1,
          },
          {
            id: 'sudoku-g2-box',
            type: 'shape',
            shapeType: 'rectangle',
            x: 455,
            y: 110,
            width: 270,
            height: 270,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: 'transparent',
            strokeColor: '#1F2937',
            strokeWidth: 2,
            borderRadius: 2,
          },
          // Grid 3 Bottom-Left
          {
            id: 'sudoku-g3-title',
            type: 'text',
            content: 'Puzzle #03',
            x: 80,
            y: 415,
            width: 300,
            height: 20,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 13,
            fontWeight: '600',
            textAlign: 'center',
            color: '#374151',
            lineHeight: 1,
            letterSpacing: 1,
          },
          {
            id: 'sudoku-g3-box',
            type: 'shape',
            shapeType: 'rectangle',
            x: 95,
            y: 440,
            width: 270,
            height: 270,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: 'transparent',
            strokeColor: '#1F2937',
            strokeWidth: 2,
            borderRadius: 2,
          },
          // Grid 4 Bottom-Right
          {
            id: 'sudoku-g4-title',
            type: 'text',
            content: 'Puzzle #04',
            x: 440,
            y: 415,
            width: 300,
            height: 20,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 13,
            fontWeight: '600',
            textAlign: 'center',
            color: '#374151',
            lineHeight: 1,
            letterSpacing: 1,
          },
          {
            id: 'sudoku-g4-box',
            type: 'shape',
            shapeType: 'rectangle',
            x: 455,
            y: 440,
            width: 270,
            height: 270,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: 'transparent',
            strokeColor: '#1F2937',
            strokeWidth: 2,
            borderRadius: 2,
          },
          {
            id: 'sudoku-footer',
            type: 'text',
            content: 'Solutions at the back of the book • Page 1',
            x: 200,
            y: 740,
            width: 420,
            height: 20,
            rotation: 0,
            zIndex: 1,
            opacity: 0.7,
            fontFamily: 'Plus Jakarta Sans',
            fontSize: 11,
            fontWeight: '400',
            textAlign: 'center',
            color: '#6B7280',
            lineHeight: 1,
            letterSpacing: 0,
          },
        ],
      },
    ],
  },
  {
    id: 'tmpl-dot-grid-journal',
    name: 'Dot Grid Creative Journal 5mm',
    category: 'Journals',
    projectType: 'Journal',
    thumbnail: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
    description: 'Precision 5mm dot grid matrix for bullet journaling, sketching, wireframing, and custom note-taking.',
    pageSize: trim6x9,
    orientation: 'Portrait',
    pageCount: 120,
    tags: ['journal', 'dot grid', 'bullet', '6x9'],
    isPopular: false,
    difficulty: 'Beginner',
    pages: [
      {
        pageNumber: 1,
        backgroundColor: '#FFFFFF',
        elements: [
          {
            id: 'dg-header',
            type: 'text',
            content: 'TOPIC: _____________________________    DATE: ___/___/2026',
            x: 50,
            y: 45,
            width: 476,
            height: 24,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'JetBrains Mono',
            fontSize: 11,
            fontWeight: '500',
            textAlign: 'left',
            color: '#6B7280',
            lineHeight: 1,
            letterSpacing: 0.5,
          },
          {
            id: 'dg-box-frame',
            type: 'shape',
            shapeType: 'rectangle',
            x: 50,
            y: 80,
            width: 476,
            height: 680,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: 'transparent',
            strokeColor: '#E5E7EB',
            strokeWidth: 1,
            borderRadius: 4,
          },
          {
            id: 'dg-center-dots',
            type: 'text',
            content: '•   •   •   •   •   •   •   •   •   •   •   •   •   •   •   •\n\n•   •   •   •   •   •   •   •   •   •   •   •   •   •   •   •\n\n•   •   •   •   •   •   •   •   •   •   •   •   •   •   •   •\n\n•   •   •   •   •   •   •   •   •   •   •   •   •   •   •   •\n\n•   •   •   •   •   •   •   •   •   •   •   •   •   •   •   •\n\n•   •   •   •   •   •   •   •   •   •   •   •   •   •   •   •\n\n•   •   •   •   •   •   •   •   •   •   •   •   •   •   •   •\n\n•   •   •   •   •   •   •   •   •   •   •   •   •   •   •   •\n\n•   •   •   •   •   •   •   •   •   •   •   •   •   •   •   •',
            x: 70,
            y: 110,
            width: 436,
            height: 620,
            rotation: 0,
            zIndex: 1,
            opacity: 0.4,
            fontFamily: 'JetBrains Mono',
            fontSize: 14,
            fontWeight: '400',
            textAlign: 'center',
            color: '#9CA3AF',
            lineHeight: 2.2,
            letterSpacing: 2,
          },
        ],
      },
    ],
  },
  {
    id: 'tmpl-kids-activity-maze',
    name: 'Kids Adventure Activity Page',
    category: 'Activity Books',
    projectType: 'Activity Book',
    thumbnail: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=400&auto=format&fit=crop&q=80',
    description: 'Engaging children activity layout combining maze illustration frame, fun prompt instructions, and decorative border.',
    pageSize: trim85x11,
    orientation: 'Portrait',
    pageCount: 50,
    tags: ['kids', 'maze', 'activity', '8.5x11'],
    isPopular: false,
    difficulty: 'Easy',
    pages: [
      {
        pageNumber: 1,
        backgroundColor: '#FFFFFF',
        elements: [
          {
            id: 'kids-title',
            type: 'text',
            content: '⭐ HELP THE PUPPY FIND HOME! ⭐',
            x: 60,
            y: 50,
            width: 700,
            height: 38,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 22,
            fontWeight: '800',
            textAlign: 'center',
            color: '#1E293B',
            lineHeight: 1.2,
            letterSpacing: 1,
          },
          {
            id: 'kids-instruction',
            type: 'text',
            content: 'Draw a path through the winding labyrinth without touching the walls!',
            x: 60,
            y: 95,
            width: 700,
            height: 24,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Plus Jakarta Sans',
            fontSize: 14,
            fontWeight: '500',
            textAlign: 'center',
            color: '#64748B',
            lineHeight: 1,
            letterSpacing: 0,
          },
          {
            id: 'kids-maze-box',
            type: 'shape',
            shapeType: 'rectangle',
            x: 160,
            y: 140,
            width: 500,
            height: 500,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: 'transparent',
            strokeColor: '#334155',
            strokeWidth: 3,
            borderRadius: 8,
          },
          {
            id: 'kids-start-label',
            type: 'text',
            content: '🐶 START',
            x: 120,
            y: 150,
            width: 80,
            height: 24,
            rotation: 0,
            zIndex: 2,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 14,
            fontWeight: '700',
            textAlign: 'right',
            color: '#0F172A',
            lineHeight: 1,
            letterSpacing: 0,
          },
          {
            id: 'kids-finish-label',
            type: 'text',
            content: '🏡 HOME',
            x: 620,
            y: 600,
            width: 90,
            height: 24,
            rotation: 0,
            zIndex: 2,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 14,
            fontWeight: '700',
            textAlign: 'left',
            color: '#0F172A',
            lineHeight: 1,
            letterSpacing: 0,
          },
          {
            id: 'kids-bonus',
            type: 'text',
            content: 'BONUS: Color the puppy and the cozy house when you reach the finish line!',
            x: 60,
            y: 670,
            width: 700,
            height: 24,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 13,
            fontWeight: '600',
            textAlign: 'center',
            color: '#475569',
            lineHeight: 1,
            letterSpacing: 0.5,
          },
        ],
      },
    ],
  },
  {
    id: 'tmpl-mandala-coloring-page',
    name: 'Botanical Floral Coloring Frame',
    category: 'Coloring Books',
    projectType: 'Coloring Book',
    thumbnail: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=400&auto=format&fit=crop&q=80',
    description: 'Crisp high-contrast vector coloring frame with intricate geometric floral ring and serene center quote.',
    pageSize: trim85x11,
    orientation: 'Portrait',
    pageCount: 40,
    tags: ['coloring', 'botanical', 'relaxation', 'adults'],
    isPopular: true,
    difficulty: 'Intermediate',
    pages: [
      {
        pageNumber: 1,
        backgroundColor: '#FFFFFF',
        elements: [
          {
            id: 'col-outer-border',
            type: 'shape',
            shapeType: 'rectangle',
            x: 50,
            y: 50,
            width: 720,
            height: 950,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: 'transparent',
            strokeColor: '#000000',
            strokeWidth: 3,
            borderRadius: 4,
          },
          {
            id: 'col-inner-border',
            type: 'shape',
            shapeType: 'rectangle',
            x: 65,
            y: 65,
            width: 690,
            height: 920,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: 'transparent',
            strokeColor: '#000000',
            strokeWidth: 1,
            borderRadius: 2,
          },
          {
            id: 'col-center-quote',
            type: 'text',
            content: 'B L O O M\nWHERE YOU ARE\nPLANTED',
            x: 150,
            y: 430,
            width: 520,
            height: 140,
            rotation: 0,
            zIndex: 2,
            opacity: 1,
            fontFamily: 'Outfit',
            fontSize: 32,
            fontWeight: '800',
            textAlign: 'center',
            color: '#000000',
            lineHeight: 1.3,
            letterSpacing: 4,
          },
          {
            id: 'col-center-ring',
            type: 'shape',
            shapeType: 'circle',
            x: 185,
            y: 290,
            width: 450,
            height: 450,
            rotation: 0,
            zIndex: 1,
            opacity: 1,
            fillColor: 'transparent',
            strokeColor: '#000000',
            strokeWidth: 2,
          },
        ],
      },
    ],
  },
];
